package actionbazaar.buslogic;

import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 100408.1504.05443)

public class PlaceBidServicePortClient
{
  @WebServiceRef
  private static PlaceBidService_Service placeBidService_Service;
  private static Logger logger;
  public static void main(String [] args)
  {
    // Add your code to call the desired methods.
    try {
        URL url = new URL("http://localhost:7101/PlaceBidBean/PlaceBidService?WSDL");
        QName serviceName = new QName("http://buslogic.actionbazaar/", "PlaceBidService");
        placeBidService_Service = new PlaceBidService_Service(url, serviceName);
        PlaceBidService placeBidService = placeBidService_Service.getPlaceBidServicePort();
        System.out.println("invoke service described at " + "http://localhost:7101/PlaceBidBean/PlaceBidService?WSDL");
        System.out.println("Bid Successful, BidId Received is:" +placeBidService.addBid("idiot",  Long.valueOf(1),  2000005.60 ));            
    }  catch (Exception ex) {
            ex.printStackTrace();
            logger.log(Level.ALL,
                     "Error in PlaceBidServicePortClient",
                      ex);
            
        }
    
  }
}
